server:
  port: 9090
dubbo:
  scan:
    base-packages: fast.cloud.nacos.dubbo.server
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
spring:
  application:
    name: dubbo-spring-cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
  main:
    allow-bean-definition-overriding: true